## Importing libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Loading dataset 

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
df = pd.read_csv('EDA_data.csv')
df.head(2)

Unnamed: 0                                  Job Title  \
0           0                           Data Scientist 1   
1           1  Data Scientist - Statistics, Early Career   

               Salary Estimate  \
0  $57K-$94K\n(Glassdoor Est.)   
1  $56K-$97K\n(Glassdoor Est.)   

                                     Job Description  Rating  \
0  at ngl, we strive to make data-driven decision...     3.2   
1   organization and job id   job id: 310918  dir...     3.8   

                                    Company Name      Location  \
0  National Guardian Life Insurance Company\n3.2   Madison, WI   
1                                      PNNL\n3.8  Richland, WA   

                     Size  Founded  Type of ownership            Industry  \
0    201 to 500 Employees     1909  Company - Private  Insurance Carriers   
1  1001 to 5000 Employees     1965         Government              Energy   

                         Sector                           Revenue  \
0                     Insurance  $500 million to $1 billion (USD)   
1  Oil, Gas, Energy & Utilities  $500 million to $1 billion (USD)   

   Hourly_salary  Employ_prov_salary  min_salary  max_salary  avg_salary  \
0              0                   0          57          94        75.5   
1              0                   0          56          97        76.5   

                                Company_txt job_state  Age_of_company  python  \
0  National Guardian Life Insurance Company        WI             111       0   
1                                      PNNL        WA              55       0   

   R  excel  sql  spark  tableau  aws  hadoop  job_simplified job_seniority  \
0  1      1    0      0        1    0       0  data scientist            na   
1  1      1    0      0        0    0       0  data scientist        junior   

   descpn_lngth  
0          2432  
1          5278

In [4]:
df = df.drop('Unnamed: 0', axis = 1)
df1 = df.copy()
df1.head(1)

Job Title              Salary Estimate  \
0  Data Scientist 1  $57K-$94K\n(Glassdoor Est.)   

                                     Job Description  Rating  \
0  at ngl, we strive to make data-driven decision...     3.2   

                                    Company Name     Location  \
0  National Guardian Life Insurance Company\n3.2  Madison, WI   

                   Size  Founded  Type of ownership            Industry  \
0  201 to 500 Employees     1909  Company - Private  Insurance Carriers   

      Sector                           Revenue  Hourly_salary  \
0  Insurance  $500 million to $1 billion (USD)              0   

   Employ_prov_salary  min_salary  max_salary  avg_salary  \
0                   0          57          94        75.5   

                                Company_txt job_state  Age_of_company  python  \
0  National Guardian Life Insurance Company        WI             111       0   

   R  excel  sql  spark  tableau  aws  hadoop  job_simplified job_seniority  \
0  1      1    0      0        1    0       0  data scientist            na   

   descpn_lngth  
0          2432

In [5]:
#TO DO
#choose relevent columns
#dummies
#test train split
#models
#tune using grid search
#test

## creating dummies

In [6]:
df1.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Size', 'Founded', 'Type of ownership',
       'Industry', 'Sector', 'Revenue', 'Hourly_salary', 'Employ_prov_salary',
       'min_salary', 'max_salary', 'avg_salary', 'Company_txt', 'job_state',
       'Age_of_company', 'python', 'R', 'excel', 'sql', 'spark', 'tableau',
       'aws', 'hadoop', 'job_simplified', 'job_seniority', 'descpn_lngth'],
      dtype='object')

In [7]:
df2 = df1[[ 'Rating','Size','Type of ownership', 'Sector', 'Revenue','job_state','Age_of_company', 'Industry',
           'python', 'R', 'excel', 'sql', 'spark', 'tableau','aws', 'hadoop', 'Hourly_salary', 'Employ_prov_salary',
           'job_simplified','job_seniority', 'descpn_lngth', 'avg_salary']]
df_dummies = pd.get_dummies(df2)
df_dummies.head(3)

Rating  Age_of_company  python  R  excel  sql  spark  tableau  aws  hadoop  \
0     3.2             111       0  1      1    0      0        1    0       0   
1     3.8              55       0  1      1    0      0        0    0       0   
2     3.9              26       0  1      0    1      1        0    1       1   

   Hourly_salary  Employ_prov_salary  descpn_lngth  avg_salary  \
0              0                   0          2432        75.5   
1              0                   0          5278        76.5   
2              0                   0          4752       116.5   

   Size_1 to 50 Employees  Size_10000+ Employees  Size_1001 to 5000 Employees  \
0                       0                      0                            0   
1                       0                      0                            1   
2                       0                      1                            0   

   Size_201 to 500 Employees  Size_5001 to 10000 Employees  \
0                          1                             0   
1                          0                             0   
2                          0                             0   

   Size_501 to 1000 Employees  Size_51 to 200 Employees  \
0                           0                         0   
1                           0                         0   
2                           0                         0   

   Type of ownership_College / University  \
0                                       0   
1                                       0   
2                                       0   

   Type of ownership_Company - Private  Type of ownership_Company - Public  \
0                                    1                                   0   
1                                    0                                   0   
2                                    0                                   1   

   Type of ownership_Government  Type of ownership_Nonprofit Organization  \
0                             0                                         0   
1                             1                                         0   
2                             0                                         0   

   Type of ownership_Other Organization  \
0                                     0   
1                                     0   
2                                     0   

   Type of ownership_Subsidiary or Business Segment  Sector_-1  \
0                                                 0          0   
1                                                 0          0   
2                                                 0          0   

   Sector_Accounting & Legal  Sector_Aerospace & Defense  \
0                          0                           0   
1                          0                           0   
2                          0                           0   

   Sector_Agriculture & Forestry  Sector_Arts, Entertainment & Recreation  \
0                              0                                        0   
1                              0                                        0   
2                              0                                        0   

   Sector_Biotech & Pharmaceuticals  Sector_Business Services  \
0                                 0                         0   
1                                 0                         0   
2                                 0                         0   

   Sector_Consumer Services  Sector_Education  Sector_Finance  \
0                         0                 0               0   
1                         0                 0               0   
2                         0                 0               0   

   Sector_Government  Sector_Health Care  Sector_Information Technology  \
0                  0                   0                              0   
1                  0                   0                              0   
2                  0                   0                        

In [8]:
df_dummies.shape

(462, 155)

## splitting dataset 

In [9]:
X = df_dummies.drop("avg_salary", axis = 1)
y = df_dummies.avg_salary.values
print("shape of X = ", X.shape)
print("shape of y = ", y.shape)

shape of X =  (462, 154)
shape of y =  (462,)


## train test split

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X,y, test_size = 0.10, random_state=51)
print("shape of X_train = ", X_train.shape)
print("shape of y_train = ", y_train.shape)
print("shape of X_test = ", X_test.shape)
print("shape of y_test = ", y_test.shape)

shape of X_train =  (415, 154)
shape of y_train =  (415,)
shape of X_test =  (47, 154)
shape of y_test =  (47,)


In [11]:
#scaling the features
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

## models

In [12]:
from sklearn.metrics import confusion_matrix, r2_score
from sklearn.model_selection import cross_val_score

In [13]:
#linear regg
import sklearn.linear_model as linear_model
LR = linear_model.LinearRegression()
LR.fit(X_train, y_train)
y_pred_lr = LR.predict(X_test)
r2_score(y_test, y_pred_lr)

0.6155928564353403

In [14]:
cross_val_score(LR, X_train, y_train, scoring = 'neg_mean_squared_error', cv = 3 )

array([ -863.2608026 , -1133.62598325,  -732.4386339 ])

In [15]:
cross_val_score(LR, X_train, y_train, scoring = 'r2', cv = 3 )

array([0.35333213, 0.21041318, 0.35393818])

In [16]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred_lr)

17.994387205276098

In [17]:
#ridge 
LRRidge = linear_model.Ridge()
LRRidge.fit(X_train, y_train)
y_pred_lrridge = LRRidge.predict(X_test)
r2_score(y_test, y_pred_lrridge)

0.7071425541593592

In [18]:
cross_val_score(LRRidge, X_train, y_train, scoring = 'neg_mean_squared_error', cv = 4 )

array([-691.4137532 , -456.57906602, -431.19888549, -391.19515976])

In [19]:
#lasso
LRLasso = linear_model.Lasso()
LRLasso.fit(X_train, y_train)
y_pred_lrlasso = LRLasso.predict(X_test)
r2_score(y_test, y_pred_lrlasso)

0.5938830660131602

In [20]:
cross_val_score(LRLasso, X_train, y_train, scoring = 'neg_mean_squared_error', cv = 3 )

array([-638.95196741, -547.44214135, -474.07197307])

In [21]:
#svm
from sklearn.svm import SVR
svr_reg2 = SVR(kernel = 'rbf')
svr_reg2.fit(X_train, y_train)
y_pred_svr2 = svr_reg2.predict(X_test)
r2_score(y_test, y_pred_svr2)

-0.08891297777986695

In [22]:
svr_reg3 = SVR(kernel = 'rbf')
svr_reg3.fit(X_train_sc, y_train)
y_pred_svr3 = svr_reg3.predict(X_test_sc)
r2_score(y_test, y_pred_svr3)

0.04635232709752368

In [23]:
cross_val_score(LRLasso, X_train, y_train, scoring = 'neg_mean_squared_error', cv = 3 )

array([-638.95196741, -547.44214135, -474.07197307])

In [24]:
#random forest
from sklearn.ensemble import RandomForestRegressor
rf_reg = RandomForestRegressor(n_estimators = 140)
rf_reg.fit(X_train, y_train)
y_pred_rf = rf_reg.predict(X_test)
r2_score(y_test, y_pred_rf)

0.6345494435094556

In [25]:
cross_val_score(rf_reg, X_train, y_train, scoring = 'neg_mean_squared_error', cv = 3 )

array([-409.86805654, -358.7830505 , -287.32674412])

In [26]:
cross_val_score(rf_reg, X_train, y_train, scoring = 'r2', cv = 3 )

array([0.6963461 , 0.7463422 , 0.72842711])

In [27]:
np.mean(cross_val_score(rf_reg, X_train, y_train, scoring = 'r2', cv = 3 ))

0.7236112719742546

In [28]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred_rf)

14.970516717325227

## pickling 

In [32]:
# Pickle
import pickle

In [33]:
# save model
pickle.dump(rf_reg, open('salary_predictor.pickle', 'wb'))

In [34]:
# load model
salary_predictor_model = pickle.load(open('salary_predictor.pickle', 'rb'))

In [35]:
# predict the output
y_pred = salary_predictor_model.predict(X_test)

In [36]:
# show the accuracy
print('Mean absolute error of random forest model = ',mean_absolute_error(y_test, y_pred_rf))

Mean absolute error of random forest model =  14.970516717325227
